Checks the potfile before it starts cracking the hash
Signed-off-by: Nimish Dudhe <20cs3043@rgipt.ac.in>

diff --git a/crackcatmod b/crackcatmod
--- a/crackcatmod
+++ b/crackcatmod
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+touch /home/$(whoami)/.local/share/hashcat/hashcat.potfile
+
 hash=$1
 cracked=0
 not_installed=0
@@ -29,14 +31,14 @@ touch /tmp/crack
 
 x=$(timeout 2 hashcat $hash 2>/dev/null >/tmp/abcd; cat /tmp/abcd | grep "your input" | cut -d " " -f 8)
 
+echo -e "\033[1;32m[+] Finding Possible Hash Types\033[0m"
+
 if [ "$x" == "only" ]
 then
 	cat /tmp/abcd | grep "your input" -C 2 | tail -n 1 >/tmp/possible-hashtypes
 else
 	hashcat $hash 2>/dev/null | grep "your input" -A $((x+3)) | tail -n $x 2>/dev/null | awk '{$1=$1};1' >/tmp/possible-hashtypes
 fi
-
-echo -e "\033[1;32m[+] Finding Possible Hash Types\033[0m"
 
 if [ $(cat /tmp/possible-hashtypes | wc -l) -eq 0 ]
 then
@@ -55,6 +57,20 @@ do
 	echo -e "  \033[1;35;43m $line \033[0m"
 done
 
+cat /home/$(whoami)/.local/share/hashcat/hashcat.potfile | grep -i $hash >/dev/null
+if [ $? -eq 0 ]
+then
+        echo -e "\033[1;32m[+] Found The Hash in Potfile\033[0m"
+        echo $hash | grep ":" > /dev/null
+        if [ $? -eq 0 ]
+        then
+                cat "/home/$(whoami)/.local/share/hashcat/hashcat.potfile" | grep -i $hash | cut -d ":" -f 3 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
+        else
+                cat "/home/$(whoami)/.local/share/hashcat/hashcat.potfile" | grep -i $hash | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
+        fi
+	exit
+fi
+
 if [ $# -eq 1 ] & [ ! -f "/usr/share/wordlists/rockyou.txt" ]
 then
 	echo "The file rockyou.txt doesn't seem to exist at its default path, You need to pass a wordlist."
@@ -62,6 +78,9 @@ then
 fi
 
 n=$(cat /tmp/possible-hashtypes | wc -l)
+
+echo ""
+echo -e "\033[1;32m[+] Trying To Crack Different Possible Hash Types\033[0m"
 
 for (( i=1; i<=$n; i++))
 do
@@ -78,6 +97,7 @@ do
 		if [ $? -ne 0 ]
 		then
 			echo -e "\033[1;35;47m $(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1') \033[0m Failed"
+			echo ''
 			continue
 		else
 			cracked=1
@@ -87,6 +107,7 @@ do
 		if [ $? -ne 0 ]
 		then
 			echo -e "\033[1;35;47m $(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1') \033[0m Failed"
+			echo ''
 			continue
 		else
 			cracked=1
@@ -100,7 +121,7 @@ do
 		cat /tmp/crack | grep Cracked >/dev/null
 		if [ $? -eq 0 ]
 		then
-			echo $hash | grep ":"
+			echo $hash | grep ":" > /dev/null
 			if [ $? -eq 0 ]
 			then
 				cat /tmp/crack | grep Cracked -B 3 | head -n 1 | cut -d ":" -f 3 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
@@ -108,19 +129,16 @@ do
 				cat /tmp/crack | grep Cracked -B 3 | head -n 1 | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
 			fi
 			exit
-		else
-			echo -e "\033[1;32m[+] Found The Hash in Potfile\033[0m"
-			cat "/home/$(whoami)/.local/share/hashcat/hashcat.potfile" | grep -i $hash | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
-			exit
 		fi
 	else
 		continue
 	fi
 done
 
-rm /tmp/crack /tmp/err /tmp/possible-hashtypes
+rm /tmp/crack /tmp/err /tmp/possible-hashtypes /tmp/abcd
 
 if [ $cracked -eq 0 ]
 then
-	echo -e "\033[1;31;47m Password Not Found In Wordlist \033[0m"
+	echo -e "\033[1;31;47m Password Not Found In Wordlist/The hash type doesn't match \033[0m"
 fi
+
