Fixed bug : Iterating over the different types of hashes.
Signed-off-by: Nimish Dudhe <20cs3043@rgipt.ac.in>

diff --git a/crackcatmod b/crackcatmod
--- a/crackcatmod
+++ b/crackcatmod
@@ -39,29 +39,43 @@ done
 
 if [ $# -eq 1 ] & [ ! -f "/usr/share/wordlists/rockyou.txt" ]
 then
-	echo rockyou.txt doesn\'t exist, You need to pass a wordlist.
+	echo "The file rockyou.txt doesn't seem to exist at its default path, You need to pass a wordlist."
 	exit
 fi
 
-cat /tmp/possible-hashtypes | while read line
+n=$(cat /tmp/possible-hashtypes | wc -l)
+
+for (( i=1; i<=$n; i++))
 do
+	line=$(cat /tmp/possible-hashtypes | head -n $i | tail -n 1);
 
 	hashname=$(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1')
 	hashval=$(echo $line | cut -d "|" -f 1 | awk '{$1=$1};1')
 
 	echo -e "Trying \033[1;35;47m $(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1') \033[0m"
+
 	if [ $# -eq 2 ]
 	then
 		hashcat -m $hashval -a 0 -d 1 $hash $2 2>/tmp/err >/tmp/crack
-		echo $cracked 0
+		if [ $? -ne 0 ]
+		then
+			echo -e "\033[1;35;47m $(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1') \033[0m Failed"
+			continue
+		fi
+		echo $cracked 120
 	else
 		hashcat -m $hashval -a 0 -d 1 $hash /usr/share/wordlists/rockyou.txt 2>/tmp/err >/tmp/crack
-		echo $cracked 1
+		if [ $? -ne 0 ]
+		then
+			echo -e "\033[1;35;47m $(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1') \033[0m Failed"
+			continue
+		fi
+		echo $cracked 210
 	fi
 
-	echo $cracked 2
+	cat /tmp/crack | grep "Cracked\|found as potfile" >/dev/null
 
-	if [ $cracked -eq 0 ]
+	if [ $? -eq 0 ]
 	then
 		cat /tmp/crack | grep Cracked >/dev/null
 		if [ $? -eq 0 ]
@@ -73,7 +87,8 @@ do
 			cat "/home/$(whoami)/.local/share/hashcat/hashcat.potfile" | grep -i $hash | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[7;34m{}\033[0m'"
 			exit
 		fi
-	echo $cracked
+	else
+		continue
 	fi
 
 	if [ $cracked -eq 0 ]
@@ -81,6 +96,7 @@ do
 		echo not found $cracked
 		echo -e "\033[1;31mPassword Not Found In Wordlist\033[0m"
 	fi
+
 done
 
-rm /tmp/crack /tmp/err /tmp/possible-hashtypes
+# rm /tmp/crack /tmp/err /tmp/possible-hashtypes
